- index.html
- src/components/footers/Footer.tsx
- src/components/footers/footer.scss
- src/components/navbars/Navbar.tsx
> footer Feature

- src/components/navbars/Navbar.tsx
- src/pages/services/Service.tsx
- src/pages/services/service.scss
- src/routes/RouteSetup.tsx
> serviceFeature1

- package-lock.json
- package.json
- src/pages/admin/Admin.tsx
- src/pages/admin/admin.scss
- src/pages/admin/serviceManager/AddService.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/routes/RouteAdmin.tsx
- src/routes/RouteSetup.tsx
> admin UI Feature

- src/pages/services/Service.tsx
- src/pages/services/service.scss
> Service feature1

- src/components/navbars/Navbar.tsx
- src/components/navbars/navbar.scss
- src/pages/homes/components/Carousels/Carousel.tsx
- src/pages/homes/components/Layout.tsx
- src/pages/homes/components/about/About.tsx
- src/pages/homes/components/about/about.scss
- src/pages/homes/components/ourServices/OurService.tsx
> update about page

- src/routes/RouteSetup.tsx
> login page

- index.html
- src/pages/admin/Admin.tsx
- src/pages/admin/admin.scss
- src/pages/admin/serviceManager/AddService.tsx
- src/pages/admin/serviceManager/EditService.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/pages/admin/serviceManager/editService.scss
- src/pages/admin/serviceManager/listService.scss
- src/routes/RouteAdmin.tsx
> Admin detail

- index.html
- src/components/calendar/Calendar.tsx
- src/components/calendar/calendar.scss
- src/components/navbars/Navbar.tsx
- src/components/navbars/navbar.scss
- src/pages/booking/Booking.tsx
- src/pages/booking/booking.scss
- src/pages/homes/components/about/about.scss
> update BookingPage Steps

- package-lock.json
- package.json
- src/App.tsx
- src/pages/admin/Admin.tsx
- src/pages/admin/Time.tsx
- src/pages/admin/voucherManager/ListVouchers.tsx
- src/pages/admin/voucherManager/Voucher.tsx
- src/pages/admin/voucherManager/voucher.scss
- src/routes/RouteAdmin.tsx
- src/services/api/index.ts
- src/services/api/modules/voucher.module.ts
- src/stores/index.ts
- src/stores/slices/voucher.slice.ts
update Route Admin & voucher admin
> update Route Admin & voucher admin

- index.html
- src/App.tsx
- src/main.scss
- src/pages/admin/Admin.tsx
- src/pages/admin/Time.tsx
- src/pages/admin/admin.scss
- src/pages/admin/time.scss
- src/stores/slices/time.slice.ts
> time setting feature

- src/pages/login/Login.tsx
- src/services/api/index.ts
- src/services/api/modules/auth.module.ts
> login Feature Update

- src/App.tsx
- src/pages/admin/voucherManager/EditVoucher.tsx
- src/pages/admin/voucherManager/ListVouchers.tsx
- src/pages/admin/voucherManager/editVoucher.scss
- src/pages/admin/voucherManager/listvoucher.scss
- src/services/api/modules/voucher.module.ts
- src/stores/slices/voucher.slice.ts
> update Voucher CRUD

- src/pages/admin/voucherManager/ListVouchers.tsx
- src/pages/admin/voucherManager/Voucher.tsx
- src/pages/admin/voucherManager/voucher.scss
- src/pages/bookings/Booking.tsx
- src/stores/slices/voucher.slice.ts
> update voucher setting time

- src/pages/admin/serviceManager/AddService.tsx
- src/pages/admin/serviceManager/EditService.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/pages/admin/serviceManager/SearchService.tsx
- src/pages/admin/serviceManager/editService.scss
- src/pages/admin/serviceManager/service.scss
- src/pages/admin/staffManager/AddStaff.tsx
- src/pages/admin/staffManager/staff.scss
- src/services/api/modules/service.module.ts
- src/stores/slices/service.slice.ts
> Edit service

- src/App.tsx
- src/pages/admin/serviceManager/AddService.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/pages/admin/staffManager/AddStaff.tsx
- src/services/api/modules/service.module.ts
- src/stores/slices/service.slice.ts
> Admin staff

- src/pages/admin/serviceManager/ListService.tsx
- src/pages/admin/voucherManager/ListVouchers.tsx
- src/pages/admin/voucherManager/Voucher.tsx
> Search feature

- src/pages/admin/serviceManager/AddService.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/pages/admin/staffManager/AddStaff.tsx
- src/pages/admin/staffManager/ListStaff.tsx
- src/services/api/index.ts
- src/services/api/modules/staff.module.ts
- src/stores/index.ts
- src/stores/slices/staff.slice.ts
> Admin staff feature

- src/App.tsx
- src/pages/admin/serviceManager/AddService.tsx
- src/pages/admin/serviceManager/EditService.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/pages/admin/serviceManager/service.scss
- src/pages/admin/staffManager/AddStaff.tsx
- src/pages/admin/staffManager/EditStaff.tsx
- src/pages/admin/staffManager/ListStaff.tsx
- src/pages/admin/staffManager/staff.scss
- src/services/api/modules/staff.module.ts
- src/stores/slices/staff.slice.ts
> staffManager

- package-lock.json
- package.json
- src/components/calendarAntd/CalendarAntd.tsx
- src/components/timePicker/TimePicker.tsx
- src/components/timePicker/TimePickerAll.tsx
- src/components/timePicker/timePicker.scss
- src/pages/admin/voucherManager/Voucher.tsx
- src/pages/booking/Booking.tsx
- src/pages/booking/booking.scss
- src/pages/thanks/Thanks.tsx
- src/services/api/modules/voucher.module.ts
- src/stores/slices/service.slice.ts
> booking Appointment Feature

- src/App.tsx
- src/components/timePicker/TimePicker.tsx
- src/pages/admin/serviceManager/EditService.tsx
- src/pages/admin/voucherManager/EditVoucher.tsx
- src/pages/admin/voucherManager/ListVouchers.tsx
- src/pages/admin/voucherManager/Voucher.tsx
- src/pages/booking/Booking.tsx
- src/pages/homes/components/banners/Banner.tsx
- src/pages/login/Login.tsx
- src/pages/thanks/Thanks.tsx
- src/routes/RouteSetup.tsx
> update booking step

- src/pages/admin/Time.tsx
- src/pages/admin/appointmentManager/AppointmentDetail.tsx
- src/pages/admin/appointmentManager/ListAppointment.tsx
- src/pages/admin/appointmentManager/appointmentDetail.scss
- src/pages/admin/appointmentManager/listAppointment.scss
- src/pages/admin/time.scss
- src/services/api/index.ts
- src/services/api/modules/appointment.module.ts
- src/stores/slices/appointment.slice.ts
update Appointment Management feature
> update Appointment Management feature

- src/pages/admin/appointmentManager/AppointmentDetail.tsx
> update Status Appointment

- src/pages/admin/customerManager/CustomerDetail.tsx
- src/pages/admin/serviceManager/ListService.tsx
- src/stores/slices/customer.slice.ts
> adminCustomer

- src/App.tsx
- src/components/notification/Notification.tsx
- src/pages/admin/chartManager/Chart.tsx
- src/pages/admin/chartManager/ChartService.tsx
- src/pages/thanks/Thanks.tsx
- src/stores/slices/appointment.slice.ts
update chart service, notification UI
> update chart service, notification UI

- src/pages/admin/appointmentManager/AppointmentDetail.tsx
- src/pages/admin/appointmentManager/appointmentDetail.scss
- src/pages/admin/appointmentManager/listAppointment.scss
- src/pages/admin/customerManager/customer.scss
> update appointment UI

- src/components/notification/Notification.tsx
- src/components/notification/notification.scss
- src/pages/admin/Time.tsx
- src/pages/admin/time.scss
- src/stores/slices/time.slice.ts
> update Notification UI

- package-lock.json
- package.json
- src/pages/admin/appointmentManager/AppointmentDetail.tsx
- src/pages/admin/appointmentManager/ListAppointment.tsx
- src/pages/admin/appointmentManager/appointmentDetail.scss
- src/pages/admin/appointmentManager/listAppointment.scss
- src/pages/thanks/Thanks.tsx
> appointment CSS

- package-lock.json
- package.json
- src/helpers/api.ts
- src/pages/login/Login.tsx
- src/services/api/modules/appointment.module.ts
- src/services/api/modules/service.module.ts
- src/services/api/modules/staff.module.ts
- src/services/api/modules/time.module.ts
- src/services/api/modules/voucher.module.ts
- tsconfig.json
- vite.config.ts
> Login api feature

- src/pages/admin/appointmentManager/ListAppointment.tsx
- src/pages/login/Login.tsx
- src/routes/PrivateRoutes.tsx
- src/routes/RouteAdmin.tsx
- src/services/api/modules/auth.module.ts
- src/services/api/modules/time.module.ts
> loginApiFeature

- src/routes/RouteAdmin.tsx
> routerAdmin
